### ISSUE TITLE
No smart contracts in new style Api

### ISSUE THREAD

**Issue by Globik** [bitaps-com/wallet-api-examples#1]
Is there any smart contract in new style API? I can't see this in docs on website. Any support of smart contracts in BTC?

**Comment by 4tochka** [comment]
Smart contract in new API is modified
Example with fixed amount
curl -X POST \
  https://api.bitaps.com/btc/v1/create/payment/address/distribution \
  -H 'Content-Type: application/json' \
  -H 'cache-control: no-cache' \
  -d '{
 "forwarding_address_primary": "37P8thrtDXb6Di5E7f4FL3bpzum3fhUvT7",
	"forwarding_address_secondary":"194zMcwXswZtkMdpoX9BYDc4T4iGqW1G61",
	"forwarding_address_primary_share":"20000"
}'

Example with percent

curl -X POST \
  https://api.bitaps.com/btc/v1/create/payment/address/distribution \
  -H 'Content-Type: application/json' \
  -H 'cache-control: no-cache' \
  -d '{
 "forwarding_address_primary": "37P8thrtDXb6Di5E7f4FL3bpzum3fhUvT7",
	"forwarding_address_secondary":"194zMcwXswZtkMdpoX9BYDc4T4iGqW1G61",
	"forwarding_address_primary_share":"10%"
}'

It not yet implemented for LTC, ETH, BCH. Once it will be implemented we will add to docs.

**Comment by Globik** [comment]
@4tochka  , thanx. Could be used the smart contract like that with test bitcoins?

**Comment by 4tochka** [comment]
yes just use testnet endpoint
