### ISSUE TITLE
ERROR 304

### ISSUE THREAD

**Issue by HackinwaleDev** [bitaps-com/wallet-api-examples#2]
I am not getting any response while trying to create wallet. Does it mean this API does not support NodeJs or what was I doing wrong?

**Comment by 4tochka** [comment]
Could you provide more details ?

**Comment by HackinwaleDev** [comment]
Sure! Below is my implementation around the endpoint given to me:


const request = require('request');
const BASE_URI = "https://api.bitaps.com/btc/testnet/v1/";

### Creating module (bitaps_com.js)
module.exports = {
    // Let's create the wallet 
    createAdminWallet: (walletCallbackUri) => {
        let options = {callback_link: walletCallbackUri, password: "mypassword"}
        return new Promise(() => {
            request.post(BASE_URI+"/create/wallet", options);
        });
    }
}

### Using the module (index.js)
 const bitaps = require('../bitaps_com');
  const {createAdminWallet} = bitaps;

  let callbackUrl = 'http://myhostname/wallet/report'
  createAdminWallet(callbackUrl)
    .then(response =>{
      console.log('=========Wallet Created Successfully=======')
      console.log(response.wallet_id +' --- '+ response.currency);
    })
    .catch(err => {
        console.log('========Failed to create wallet==========');
        console.log(err);
    });


Pls kindly check and see what I am doing wrong. thanks.

**Comment by HackinwaleDev** [comment]
Fixed now. I was wrapping request.post in Promise whereas it is a promise itself.

_return request.post((BASE_URI+"/create/wallet", options);_ is the right way

Thanks.
